trigger: hz(20, hour)
channel: db
metadata:
  table: positions
schema:
  type: object
  properties:
    id:
      type: string
      pattern: "[a-zA-Z0-9]{32}"
    user_id:
      type: function
      expression: user.id
      variables:
        user:
          type: reference
          effect: users.create
    take_id:
      type: function
      expression: take.id
      variables:
        take:
          type: reference
          effect: takes.create
    stance:
      type: select
      options:
        - weight: 3
          schema: { type: constant, value: agree }
        - weight: 2
          schema: { type: constant, value: disagree }
    created_at:
      type: context
      path: ["clock", "now"]
    deleted_at:
      type: constant
      value: null
