trigger: hz(2, hour)
channel: db
metadata:
  table: users
schema:
  type: object
  properties:
    id:
      type: string
      pattern: "[a-zA-Z0-9]{32}"
    name:
      type: string
      pattern: "[A-Za-z]{3,12} [A-Za-z]{3,15}"
    email:
      type: function
      expression: "local + string(n) + '@' + domain"
      variables:
        local:
          type: string
          pattern: "[a-z]{4,10}"
        n:
          type: number
          minimum: 1
          maximum: 99999
          scale: 0
        domain:
          type: select
          options:
            - weight: 3
              schema: { type: constant, value: "gmail.com" }
            - weight: 2
              schema: { type: constant, value: "yahoo.com" }
            - weight: 2
              schema: { type: constant, value: "outlook.com" }
            - schema: { type: constant, value: "icloud.com" }
            - schema: { type: constant, value: "proton.me" }
    email_verified:
      type: select
      options:
        - weight: 7
          schema: { type: constant, value: true }
        - weight: 3
          schema: { type: constant, value: false }
    image:
      type: select
      options:
        - weight: 3
          schema:
            type: function
            expression: "'https://assets.ui.sh/avatars/' + string(n) + '.webp'"
            variables:
              n:
                type: number
                minimum: 1
                maximum: 100
                scale: 0
        - weight: 1
          schema: { type: constant, value: null }
    created_at:
      type: context
      path: ["clock", "now"]
    updated_at:
      type: context
      path: ["clock", "now"]
